### ISSUE TITLE
In the event mode, it does not show the year correctly.

### ISSUE THREAD

**Issue by josevidalrt** [ubports/gallery-app#73]
In the event mode, it does not show the year correctly.
![screenshot20180818_231506845](https://user-images.githubusercontent.com/12157729/44303274-d7e0cf80-a33c-11e8-96aa-fa4414265f2f.png)

**Comment by Flohack74** [comment]
Works for me, which language do you use? Spanish?
![grafik](https://user-images.githubusercontent.com/16186470/44307076-73555d00-a39c-11e8-87f4-a4f273ea3656.png)

**Comment by josevidaldoblecero** [comment]
Hi, yes it is Spanish

**Comment by Flohack74** [comment]
The problem seems to be here:
![grafik](https://user-images.githubusercontent.com/16186470/44307353-2f188b80-a3a1-11e8-8c9a-f96c55ba190c.png)

Someone translated the mask for 4-digit year. I will revert it back to yyyy...

**Comment by josevidaldoblecero** [comment]
Thanks In case it was useful, I attach the modified binary as a solution until the new version that corrects it is launched. Just unzip the .gz and replace the gallery-app.mo file located at /opt/click.ubuntu.com/com.ubuntu.gallery/2.9.8/share/locale/es

[gallery-app.mo-fix.gz](https://github.com/ubports/gallery-app/files/2300250/gallery-app.mo-fix.gz)
![screenshot20180819_123745710](https://user-images.githubusercontent.com/12157729/44308019-c97ecc00-a3ad-11e8-9516-742766237c28.png)

**Comment by StefWe** [comment]
Can we close this issue? Is this fixed in version 2.9.9?

**Comment by CesarHerreraG** [comment]
Not yet.

**Comment by StefWe** [comment]
Hm, we need to check weblate again and then release a new version.

**Comment by StefWe** [comment]
Hm, we need to check weblate again and then release a new version.

**Comment by advocatux** [comment]
I can confirm this issue is still happening in xenial devel. For example, this is a screenshot of my BQ E4.5 running 16.04 (2018-11-14) right now:
![aaaa-issue](https://user-images.githubusercontent.com/30233652/48516410-97bdba00-e863-11e8-9c59-1936e3bb8d2b.jpg)

**Comment by advocatux** [comment]
@StefWe that string looks OK in weblate https://translate.ubports.com/translate/ubports/gallery-app/es/?checksum=&offset=1&q=yyyy&search=ftx&type=all&ignored=&date=&only_user=&exclude_user=

BTW, if any string can't be "touched" it shouldn't be available for translation or should have a clear warning about what will happen if someone does it :)

**Comment by StefWe** [comment]
i checked the es.po file
![screenshot_20181114_232950](https://user-images.githubusercontent.com/35935077/48517028-529a8780-e865-11e8-8240-c781054c440e.png)
and the weblate
![screenshot_20181114_233016](https://user-images.githubusercontent.com/35935077/48517037-58906880-e865-11e8-8ead-eda90980278c.png)
both looks good. I think we need to release a new version of the app.

But why is this problem still there if you are on devel channel?

**Comment by advocatux** [comment]
I don't know, I thought this issue was fixed. I reviewed that whole translation 11 days ago and that string was fine.

I'm checking the `es.po` file now to see if there was any problem in the step from Weblate to GitHub but it looks OK too:
https://github.com/ubports/gallery-app/blob/30e2c90e88ff70283adf83c1ae21f540520fbe36/po/es.po#L103-L105

**Comment by StefWe** [comment]
I build a click from the actual master branch. Can you install that and check the translation?

[com.ubuntu.gallery_2.9.9_armhf.zip](https://github.com/ubports/gallery-app/files/2584169/com.ubuntu.gallery_2.9.9_armhf.zip)

I need to change the name of the file *.zip otherwise it is not possible to upload it. Please rename the file after download to *.click

**Comment by advocatux** [comment]
Yes, that click package works.

@StefWe thank you for your work !!

**Comment by StefWe** [comment]
@advocatux thank you for testing the click file.

What we can do now? For solving this problem for every users?
What needs to be done to bring a new click version in the open-store?

**Comment by advocatux** [comment]
@StefWe you're welcome.

Emanuele Sorce (@TronFortyTwo) is still the maintainer, so he should upload the package to the OpenStore

**Comment by advocatux** [comment]
FYI I've pinged Emanuele in the OpenStore group (TG)

**Comment by StefWe** [comment]
The new version is released. Thanks to @advocatux and @TronFortyTwo for that.

@Flohack74  i think you can close this issue now.

**Comment by StefWe** [comment]
Can anyone confirm that this issue is solved?

**Comment by advocatux** [comment]
I thought it was confirmed already.

Anyhow, I confirm that this issue is fixed :)

**Comment by StefWe** [comment]
Thank you very much for your feedback.

Now we have to find someone who wants to close a ticket :-)
